[package]
name = "ethshuffle-rs"
version = "0.1.0"
authors = ["neve noomo <d3ad.l1n3@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
